
[urgency_low]
    background = "#6573A3FF"
    foreground = "#CCD7FFFF"
    frame_color = "#6573A303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A3C6BFF"
    foreground = "#CCCFFFFF"
    frame_color = "#3A3C6B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
