local customCol = function(colors)
        local blinkBg = colors.crust
        return {

                -------------------------------------------------------------------------------------------------------------
                -- NOICE

                NoiceCmdline                     = { bg = colors.base },
                NoiceCmdlinePopup                = { bg = colors.base },
                NoiceCmdlinePopupBorder          = { fg = colors.base, bg = colors.base },

                -------------------------------------------------------------------------------------------------------------
                -- SNACKS

                SnacksPickerTitle                = { fg = colors.red },
                SnacksPicker                     = { bg = colors.crust },
                SnacksPickerCursorLine           = { bg = colors.crust, bold = true },

                SnacksNotifierBorderInfo         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierBorderWarn         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierBorderError        = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierFooterInfo         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierFooterWarn         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierFooterError        = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierTitleInfo          = { bg = colors.crust },
                SnacksNotifierTitleWarn          = { bg = colors.crust },
                SnacksNotifierTitleError         = { bg = colors.crust },
                SnacksNotifierInfo               = { bg = colors.crust },
                SnacksNotifierWarn               = { bg = colors.crust },
                SnacksNotifierError              = { bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- TELESCOPE

                TelescopePromptCount             = { fg = colors.text, bg = colors.crust },
                TelescopePromptTitle             = { fg = colors.flamingo, bg = colors.crust },
                TelescopePromptPrefix            = { fg = colors.flamingo, bg = colors.crust },
                TelescopePromptNormal            = { fg = colors.text, bg = colors.crust },
                TelescopePromptBorder            = { fg = colors.crust, bg = colors.crust },
                TelescopeResultsTitle            = { fg = colors.flamingo, bg = colors.crust },
                TelescopeResultsNormal           = { fg = colors.overlay0, bg = colors.crust },
                TelescopeResultsBorder           = { fg = colors.crust, bg = colors.crust },
                TelescopePreviewTitle            = { fg = colors.text, bg = colors.crust },
                TelescopePreviewNormal           = { fg = colors.text, bg = colors.crust },
                TelescopePreviewBorder           = { fg = colors.mantle, bg = colors.crust },
                TelescopeSelection               = { bg = colors.crust, bold = true },
                TelescopeSelectionCaret          = { bg = colors.crust, bold = true },

                -------------------------------------------------------------------------------------------------------------
                -- BLINK

                BlinkCmpLabelDescription         = { link = "NonText" },
                BlinkCmpLabelDetail              = { link = "NonText" },
                BlinkCmpMenuBorder               = { link = "Normal" },
                BlinkCmpMenu                     = { link = "Normal" },
                BlinkCmpMenuSelection            = { link = "Visual" },
                BlinkCmpSource                   = { link = "@lsp.type.type" },
                BlinkCmpAbbrDeprecated           = { fg = colors.red, bg = colors.none, strikethrough = true },

                BlinkCmpKindClass                = { link = "@lsp.type.class" },
                BlinkCmpKindColor                = { link = "@define" },
                BlinkCmpKindConstant             = { link = "@constant" },
                BlinkCmpKindConstructor          = { link = "@constructor" },
                BlinkCmpKindEnum                 = { link = "@lsp.type.enum" },
                BlinkCmpKindEnumMember           = { link = "@lsp.type.enumMember" },
                BlinkCmpKindEvent                = { link = "@lsp.type.event" },
                BlinkCmpKindField                = { link = "@field" },
                BlinkCmpKindFile                 = { link = "NonText" },
                BlinkCmpKindFolder               = { fg = "#dce0e8", bg = colors.none },
                BlinkCmpKindFunction             = { link = "@lsp.type.function" },
                BlinkCmpKindInterface            = { link = "@lsp.type.interface" },
                BlinkCmpKindKeyword              = { link = "@lsp.type.keyword" },
                BlinkCmpKindMethod               = { link = "@lsp.type.method" },
                BlinkCmpKindModule               = { link = "@module" },
                BlinkCmpKindOperator             = { link = "@lsp.type.operator" },
                BlinkCmpKindProperty             = { link = "@lsp.type.property" },
                BlinkCmpKindReference            = { fg = "#dce0e8", bg = colors.none },
                BlinkCmpKindSnippet              = { fg = colors.yellow, bg = colors.none },
                BlinkCmpKindStruct               = { link = "@lsp.type.struct" },
                BlinkCmpKindText                 = { link = "@comment" },
                BlinkCmpKindTypeParameter        = { link = "@lsp.type.typeParameter" },
                BlinkCmpKindUnit                 = { fg = colors.yellow, bg = colors.none },
                BlinkCmpKindValue                = { link = "@lsp.type.boolean" },
                BlinkCmpKindVariable             = { link = "@lsp.type.type" },

                -------------------------------------------------------------------------------------------------------------
                -- MISC

                ActiveLineNumber                 = { fg = colors.subtext0 },
                CursorLineNr                     = { fg = colors.flamingo, bg = colors.crust },
                DiagnosticError                  = { bg = colors.crust },
                DiagnosticInfo                   = { bg = colors.crust },
                DiagnosticWarn                   = { bg = colors.crust },
                FloatBorder                      = { fg = colors.crust, bg = colors.crust },
                Folded                           = { link = "Visual" },
                GitSignsAdd                      = { bg = colors.crust },
                GitSignsChange                   = { bg = colors.crust },
                GitSignsDelete                   = { bg = colors.crust },
                LineNr                           = { fg = colors.surface0 },
                LspInfoBorder                    = { fg = colors.subtext0, bg = colors.subtext0 },
                NoiceCmdlineIcon                 = { fg = colors.rosewater },
                Normal                           = { bg = colors.crust },
                NormalFloat                      = { bg = colors.mantle },
                NormalNC                         = { bg = colors.crust },
                Title                            = { fg = colors.subtext0 },
                TSDefinitionUsage                = { bg = colors.surface0 },
                VertSplit                        = { fg = colors.base, bg = colors.crust },
                VisualNonText                    = { fg = colors.surface0, bold = true },
                WinBar                           = { fg = colors.subtext0, bg = colors.crust },
                WinBarNC                         = { fg = colors.subtext0, bg = colors.crust },
                WinSeparator                     = { fg = colors.base, bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- NEOTREE

                NeoTreeCursorLine                = { link = "Visual" },
                NeoTreeDirectoryIcon             = { fg = "#dce0e8" },
                NeoTreeDirectoryName             = { fg = "#dce0e8" },
                NeoTreeExpander                  = { fg = colors.base },
                NeoTreeFileName                  = { link = "NonText" },
                NeoTreeFloatBorder               = { fg = colors.text },
                NeoTreeFloatNormal               = { fg = colors.text },
                NeoTreeFloatTitle                = { fg = colors.crust, bg = colors.text },
                NeoTreeGitModified               = { link = "GitSignsDelete" },
                NeoTreeGitUntracked              = { link = "GitsignsUntracked" },
                NeoTreeModified                  = { fg = colors.text },
                NeoTreeNormal                    = { link = "Normal" },
                NeoTreeNormalNC                  = { link = "NormalNC" },
                NeoTreeRootName                  = { fg = colors.flamingo },
                NeoTreeStatsHeader               = { fg = colors.base, bg = colors.base },
                NeoTreeVertSplit                 = { link = "WinSeparator" },
                NeoTreeWinSeparator              = { link = "WinSeparator" },

                -------------------------------------------------------------------------------------------------------------
                -- OUTLINE

                OutlineCurrent                   = { link = "Visual" },
                OutlineDetails                   = { link = "NonText" },
                OutlineFoldMarker                = { link = "NonText" },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR

                DropBarCurrentContext            = { bold = true },
                DropBarFzfMatch                  = { fg = colors.red, bold = true },
                DropBarHover                     = { bold = true },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR ICON UI

                DropBarIconUiIndicator           = { link = "NonText" },
                DropBarMenuCurrentContext        = { bold = true },
                DropBarMenuFloatBorder           = { fg = colors.rosewater, bg = colors.base },
                DropBarMenuHoverEntry            = { fg = colors.red, bg = colors.base },
                DropBarMenuHoverIcon             = { fg = colors.red, bg = colors.base, bold = true, reverse = true },
                DropBarMenuHoverSymbol           = { fg = colors.red, bg = colors.base, bold = true },
                DropBarMenuNormalFloat           = { link = "NormalFloat" },
                DropBarMenuSbar                  = { fg = colors.red, bg = colors.base },
                DropBarMenuThumb                 = { fg = colors.rosewater, bg = colors.base },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR KIND

                DropBarKindDefault               = { fg = colors.rosewater, bg = colors.none },
                DropBarKindArray                 = { fg = colors.rosewater, bg = colors.none },
                DropBarKindBoolean               = { link = "@lsp.type.boolean" },
                DropBarKindBreakstatement        = { fg = colors.red, bg = colors.none },
                DropBarKindCall                  = { link = "@function.call" },
                DropBarKindCasestatement         = { link = "@keyword.conditional" },
                DropBarKindClass                 = { link = "@lsp.type.class" },
                DropBarKindConstant              = { link = "@constant" },
                DropBarKindConstructor           = { link = "@constructor" },
                DropBarKindContinuestatement     = { fg = colors.lavender, bg = colors.none },
                DropBarKindDeclaration           = { fg = colors.rosewater, bg = colors.none },
                DropBarKindDelete                = { fg = colors.red, bg = colors.none },
                DropBarKindDostatement           = { fg = colors.yellow, bg = colors.none },
                DropBarKindElsestatement         = { fg = colors.sapphire, bg = colors.none },
                DropBarKindElement               = { fg = colors.rosewater, bg = colors.none },
                DropBarKindEnum                  = { link = "@lsp.type.enum" },
                DropBarKindEnumMember            = { link = "@lsp.type.enumMember" },
                DropBarKindEvent                 = { link = "@lsp.type.event" },
                DropBarKindField                 = { link = "@field" },
                DropBarKindFile                  = { fg = colors.subtext0, bg = colors.none },
                DropBarKindFolder                = { fg = "#dce0e8", bg = colors.none },
                DropBarKindForStatement          = { link = "@keyword.repeat" },
                DropBarKindFunction              = { link = "@lsp.type.function" },
                DropBarKindH1Marker              = { fg = colors.red, bg = colors.none },
                DropBarKindH2Marker              = { fg = colors.peach, bg = colors.none },
                DropBarKindH3Marker              = { fg = colors.yellow, bg = colors.none },
                DropBarKindH4Marker              = { fg = colors.green, bg = colors.none },
                DropBarKindH5Marker              = { fg = colors.sapphire, bg = colors.none },
                DropBarKindH6Marker              = { fg = colors.lavender, bg = colors.none },
                DropBarKindIdentifier            = { fg = colors.rosewater, bg = colors.none },
                DropBarKindIfStatement           = { link = "@keyword.conditional" },
                DropBarKindInterface             = { link = "@lsp.type.interface" },
                DropBarKindKeyword               = { link = "@lsp.type.keyword" },
                DropBarKindList                  = { fg = colors.rosewater, bg = colors.none },
                DropBarKindMacro                 = { link = "@lsp.type.macro" },
                DropBarKindMarkdownH1            = { fg = colors.red, bg = colors.none },
                DropBarKindMarkdownH2            = { fg = colors.peach, bg = colors.none },
                DropBarKindMarkdownH3            = { fg = colors.yellow, bg = colors.none },
                DropBarKindMarkdownH4            = { fg = colors.green, bg = colors.none },
                DropBarKindMarkdownH5            = { fg = colors.sapphire, bg = colors.none },
                DropBarKindMarkdownH6            = { fg = colors.lavender, bg = colors.none },
                DropBarKindMethod                = { link = "@lsp.type.method" },
                DropBarKindModule                = { link = "@module" },
                DropBarKindNamespace             = { link = "@lsp.type.namespace" },
                DropBarKindNull                  = { link = "@lsp.type.boolean" },
                DropBarKindNumber                = { link = "@lsp.type.number" },
                DropBarKindObject                = { link = "@keyword.return" },
                DropBarKindOperator              = { link = "@lsp.type.operator" },
                DropBarKindPackage               = { fg = colors.sapphire, bg = colors.none },
                DropBarKindPair                  = { fg = colors.rosewater, bg = colors.none },
                DropBarKindProperty              = { link = "@lsp.type.property" },
                DropBarKindReference             = { fg = colors.yellow, bg = colors.none },
                DropBarKindRepeat                = { link = "@keyword.repeat" },
                DropBarKindRuleset               = { fg = colors.rosewater, bg = colors.none },
                DropBarKindScope                 = { fg = colors.rosewater, bg = colors.none },
                DropBarKindSpecifier             = { fg = colors.rosewater, bg = colors.none },
                DropBarKindStatement             = { link = "Statement" },
                DropBarKindString                = { link = "@string" },
                DropBarKindStruct                = { link = "@lsp.type.struct" },
                DropBarKindSwitchstatement       = { fg = colors.lavender, bg = colors.none },
                DropBarKindTerminal              = { fg = colors.rosewater, bg = colors.none },
                DropBarKindType                  = { link = "@lsp.type.type" },
                DropBarKindTypeParameter         = { link = "@lsp.type.typeParameter" },
                DropBarKindUnit                  = { fg = colors.yellow, bg = colors.none },
                DropBarKindValue                 = { fg = colors.text, bg = colors.none },
                DropBarKindVariable              = { link = "@lsp.type.variable" },
                DropBarKindWhileStatement        = { link = "@keyword.repeat" },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR ICON KIND

                DropBarIconKindDefault           = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindArray             = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindBoolean           = { link = "@lsp.type.boolean" },
                DropBarIconKindBreakstatement    = { fg = colors.red, bg = colors.none },
                DropBarIconKindCall              = { link = "@function.call" },
                DropBarIconKindCasestatement     = { link = "@keyword.conditional" },
                DropBarIconKindClass             = { link = "@lsp.type.class" },
                DropBarIconKindConstant          = { link = "@constant" },
                DropBarIconKindConstructor       = { link = "@constructor" },
                DropBarIconKindContinuestatement = { fg = colors.lavender, bg = colors.none },
                DropBarIconKindDeclaration       = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindDelete            = { fg = colors.red, bg = colors.none },
                DropBarIconKindDostatement       = { fg = colors.yellow, bg = colors.none },
                DropBarIconKindElsestatement     = { fg = colors.sapphire, bg = colors.none },
                DropBarIconKindElement           = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindEnum              = { link = "@lsp.type.enum" },
                DropBarIconKindEnumMember        = { link = "@lsp.type.enumMember" },
                DropBarIconKindEvent             = { link = "@lsp.type.event" },
                DropBarIconKindField             = { link = "@field" },
                DropBarIconKindFile              = { fg = colors.subtext0, bg = colors.none },
                DropBarIconKindFolder            = { fg = "#dce0e8", bg = colors.none },
                DropBarIconKindForStatement      = { link = "@keyword.repeat" },
                DropBarIconKindFunction          = { link = "@lsp.type.function" },
                DropBarIconKindH1Marker          = { fg = colors.red, bg = colors.none },
                DropBarIconKindH2Marker          = { fg = colors.peach, bg = colors.none },
                DropBarIconKindH3Marker          = { fg = colors.yellow, bg = colors.none },
                DropBarIconKindH4Marker          = { fg = colors.green, bg = colors.none },
                DropBarIconKindH5Marker          = { fg = colors.sapphire, bg = colors.none },
                DropBarIconKindH6Marker          = { fg = colors.lavender, bg = colors.none },
                DropBarIconKindIdentifier        = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindIfStatement       = { link = "@keyword.conditional" },
                DropBarIconKindInterface         = { link = "@lsp.type.interface" },
                DropBarIconKindKeyword           = { link = "@lsp.type.keyword" },
                DropBarIconKindList              = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindMacro             = { link = "@lsp.type.macro" },
                DropBarIconKindMarkdownH1        = { fg = colors.red, bg = colors.none },
                DropBarIconKindMarkdownH2        = { fg = colors.peach, bg = colors.none },
                DropBarIconKindMarkdownH3        = { fg = colors.yellow, bg = colors.none },
                DropBarIconKindMarkdownH4        = { fg = colors.green, bg = colors.none },
                DropBarIconKindMarkdownH5        = { fg = colors.sapphire, bg = colors.none },
                DropBarIconKindMarkdownH6        = { fg = colors.lavender, bg = colors.none },
                DropBarIconKindMethod            = { link = "@lsp.type.method" },
                DropBarIconKindModule            = { link = "@module" },
                DropBarIconKindNamespace         = { link = "@lsp.type.namespace" },
                DropBarIconKindNull              = { link = "@lsp.type.boolean" },
                DropBarIconKindNumber            = { link = "@lsp.type.number" },
                DropBarIconKindObject            = { link = "@keyword.return" },
                DropBarIconKindOperator          = { link = "@lsp.type.operator" },
                DropBarIconKindPackage           = { fg = colors.sapphire, bg = colors.none },
                DropBarIconKindPair              = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindProperty          = { link = "@lsp.type.property" },
                DropBarIconKindReference         = { fg = colors.yellow, bg = colors.none },
                DropBarIconKindRepeat            = { link = "@keyword.repeat" },
                DropBarIconKindRuleset           = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindScope             = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindSpecifier         = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindStatement         = { link = "Statement" },
                DropBarIconKindString            = { link = "@string" },
                DropBarIconKindStruct            = { link = "@lsp.type.struct" },
                DropBarIconKindSwitchstatement   = { fg = colors.lavender, bg = colors.none },
                DropBarIconKindTerminal          = { fg = colors.rosewater, bg = colors.none },
                DropBarIconKindType              = { link = "@lsp.type.type" },
                DropBarIconKindTypeParameter     = { link = "@lsp.type.typeParameter" },
                DropBarIconKindUnit              = { fg = colors.yellow, bg = colors.none },
                DropBarIconKindValue             = { fg = colors.text, bg = colors.none },
                DropBarIconKindVariable          = { link = "@lsp.type.variable" },
                DropBarIconKindWhileStatement    = { link = "@keyword.repeat" },

        }
end

return {
        "catppuccin/nvim",
        lazy     = false,
        name     = "catppuccin",
        priority = 1000,
        config   = function()
                require("catppuccin").setup({
                        compile_path           = vim.fn.stdpath"cache" .. "/catppuccin",
                        flavour                = "mocha",
                        transparent_background = false,
                        show_end_of_buffer     = true,
                        term_colors            = true,
                        background             = { light = "latte", dark = "mocha" },
                        dim_inactive           = { enabled = false, shade = "dark", percentage = 0.15 },
                        no_italic              = true,
                        no_bold                = false,
                        no_underline           = false,

                        color_overrides        = {
                                mocha = {
                                        -- crust  = "#000000",
                                        -- mantle = "#000000",
                                },
                        },
                        custom_highlights      = customCol,

                        default_integrations   = true,
                        integrations           = {
                                blink_cmp        = true,
                                cmp              = true,
                                dap              = true,
                                dap_ui           = true,
                                lsp_saga         = true,
                                dashboard        = true,
                                dropbar          = {
                                        enabled    = true,
                                        color_mode = true,
                                },
                                gitsigns         = true,
                                indent_blankline = {
                                        enabled     = true,
                                        scope_color = "text",
                                },
                                mason            = true,
                                markdown         = true,
                                render_markdown  = true,
                                mini             = true,
                                native_lsp       = {
                                        enabled    = true,
                                        underlines = {
                                                -- errors      = { "undercurl" },
                                                -- hints       = { "undercurl" },
                                                -- warnings    = { "undercurl" },
                                                -- information = { "undercurl" },
                                        },
                                },
                                telescope        = true,
                                notify           = true,
                                navic            = { enabled = true, custom_bg = "lualine" },
                                neotest          = true,
                                neotree          = true,
                                noice            = true,
                                semantic_tokens  = true,
                                treesitter       = true,
                                ufo              = true,
                                which_key        = true,
                        },
                })

                vim.cmd("colorscheme catppuccin")
        end,
}
