local customCol = function(colors)
        local blinkBg = "NONE"
        return {
                -------------------------------------------------------------------------------------------------------------------
                -- CMP

                CustomPmenu                      = { bg = colors.mantle },
                CustomBorder                     = { fg = colors.mantle, bg = colors.mantle },
                --Documentation
                CmpPmenu                         = { fg = colors.text, bg = colors.mantle },
                CmpBorder                        = { fg = colors.mantle, bg = colors.mantle },

                Pmenu                            = { fg = colors.text, bg = colors.mantle },
                PmenuSel                         = { fg = colors.flamingo, bg = colors.mantle },

                CmpItemAbbrDeprecated            = { fg = colors.maroon, bg = "NONE" },
                CmpItemAbbrMatch                 = { fg = colors.text, bg = "NONE", bold = true },
                CmpItemAbbrMatchFuzzy            = { fg = colors.text, bg = "NONE", bold = true },
                CmpItemMenu                      = { fg = colors.overlay0, bg = "NONE", bold = true },
                CmpItemKindField                 = { fg = colors.rosewater, bg = "NONE" },
                CmpItemKindProperty              = { fg = colors.rosewater, bg = "NONE" },
                CmpItemKindEvent                 = { fg = colors.rosewater, bg = "NONE" },
                CmpItemKindText                  = { fg = colors.lavender, bg = "NONE" },
                CmpItemKindEnum                  = { fg = colors.lavender, bg = "NONE" },
                CmpItemKindKeyword               = { fg = colors.lavender, bg = "NONE" },
                CmpItemKindConstant              = { fg = colors.yellow, bg = "NONE" },
                CmpItemKindConstructor           = { fg = colors.yellow, bg = "NONE" },
                CmpItemKindReference             = { fg = colors.yellow, bg = "NONE" },
                CmpItemKindFunction              = { fg = "#dce0e8", bg = "NONE" },
                CmpItemKindStruct                = { fg = "#dce0e8", bg = "NONE" },
                CmpItemKindClass                 = { fg = "#dce0e8", bg = "NONE" },
                CmpItemKindModule                = { fg = "#dce0e8", bg = "NONE" },
                CmpItemKindOperator              = { fg = "#dce0e8", bg = "NONE" },
                CmpItemKindVariable              = { fg = colors.text, bg = "NONE" },
                CmpItemKindFile                  = { fg = colors.text, bg = "NONE" },
                CmpItemKindUnit                  = { fg = colors.yellow, bg = "NONE" },
                CmpItemKindSnippet               = { fg = colors.yellow, bg = "NONE" },
                CmpItemKindFolder                = { fg = colors.yellow, bg = "NONE" },
                CmpItemKindMethod                = { fg = colors.text, bg = "NONE" },
                CmpItemKindValue                 = { fg = colors.text, bg = "NONE" },
                CmpItemKindEnumMember            = { fg = colors.text, bg = "NONE" },
                CmpItemKindInterface             = { fg = colors.teal, bg = "NONE" },
                CmpItemKindColor                 = { fg = colors.teal, bg = "NONE" },
                CmpItemKindTypeParameter         = { fg = colors.teal, bg = "NONE" },

                -------------------------------------------------------------------------------------------------------------
                -- NOICE

                NoiceCmdline                     = { bg = colors.base },
                NoiceCmdlinePopup                = { bg = colors.base },
                NoiceCmdlinePopupBorder          = { fg = colors.base, bg = colors.base },

                -------------------------------------------------------------------------------------------------------------
                -- SNACKS

                SnacksPickerTitle                = { fg = colors.red },
                SnacksPicker                     = { bg = colors.crust },
                SnacksNotifierBorderInfo         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierBorderWarn         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierBorderError        = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierFooterInfo         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierFooterWarn         = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierFooterError        = { fg = colors.crust, bg = colors.crust },
                SnacksNotifierTitleInfo          = { bg = colors.crust },
                SnacksNotifierTitleWarn          = { bg = colors.crust },
                SnacksNotifierTitleError         = { bg = colors.crust },
                SnacksNotifierInfo               = { bg = colors.crust },
                SnacksNotifierWarn               = { bg = colors.crust },
                SnacksNotifierError              = { bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- MODES

                ModesCopyCursorLineNr            = { fg = colors.rosewater, bg = colors.crust },
                ModesCopyCursorLineSign          = { fg = colors.rosewater, bg = colors.crust },
                ModesCopyCursorLineFold          = { fg = colors.rosewater, bg = colors.crust },
                ModesDeleteCursorLineNr          = { fg = colors.rosewater, bg = colors.crust },
                ModesDeleteCursorLineSign        = { fg = colors.rosewater, bg = colors.crust },
                ModesDeleteCursorLineFold        = { fg = colors.rosewater, bg = colors.crust },
                ModesInsertCursorLineNr          = { fg = colors.rosewater, bg = colors.crust },
                ModesInsertCursorLineSign        = { fg = colors.rosewater, bg = colors.crust },
                ModesInsertCursorLineFold        = { fg = colors.rosewater, bg = colors.crust },
                ModesVisualCursorLineNr          = { fg = colors.rosewater, bg = colors.crust },
                ModesVisualCursorLineSign        = { fg = colors.rosewater, bg = colors.crust },
                ModesVisualCursorLineFold        = { fg = colors.rosewater, bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- BLINK

                BlinkCmpSource                   = { fg = colors.overlay1, bg = colors.crust, bold = false },
                BlinkCmpAbbrDeprecated           = { fg = colors.red, bg = blinkBg, strikethrough = false },
                BlinkCmpAbbrMatch                = { fg = colors.text, bg = blinkBg, bold = false },
                BlinkCmpAbbrMatchFuzzy           = { fg = colors.text, bg = blinkBg, bold = false },
                BlinkCmpMenu                     = { fg = colors.overlay0, bg = colors.crust, bold = false },
                BlinkCmpMenuSelection            = { fg = blinkBg, bg = colors.crust, bold = true },
                BlinkCmpKindField                = { fg = colors.rosewater, bg = blinkBg },
                BlinkCmpKindProperty             = { fg = colors.rosewater, bg = blinkBg },
                BlinkCmpKindEvent                = { fg = colors.rosewater, bg = blinkBg },
                BlinkCmpKindText                 = { fg = colors.lavender, bg = blinkBg },
                BlinkCmpKindEnum                 = { fg = colors.lavender, bg = blinkBg },
                BlinkCmpKindKeyword              = { fg = colors.lavender, bg = blinkBg },
                BlinkCmpKindConstant             = { fg = colors.yellow, bg = blinkBg },
                BlinkCmpKindConstructor          = { fg = colors.yellow, bg = blinkBg },
                BlinkCmpKindReference            = { fg = colors.yellow, bg = blinkBg },
                BlinkCmpKindFunction             = { fg = "#dce0e8", bg = blinkBg },
                BlinkCmpKindStruct               = { fg = "#dce0e8", bg = blinkBg },
                BlinkCmpKindClass                = { fg = "#dce0e8", bg = blinkBg },
                BlinkCmpKindModule               = { fg = "#dce0e8", bg = blinkBg },
                BlinkCmpKindOperator             = { fg = "#dce0e8", bg = blinkBg },
                BlinkCmpKindVariable             = { fg = colors.text, bg = blinkBg },
                BlinkCmpKindFile                 = { fg = colors.text, bg = blinkBg },
                BlinkCmpKindUnit                 = { fg = colors.yellow, bg = blinkBg },
                BlinkCmpKindSnippet              = { fg = colors.yellow, bg = blinkBg },
                BlinkCmpKindFolder               = { fg = colors.yellow, bg = blinkBg },
                BlinkCmpKindMethod               = { fg = colors.text, bg = blinkBg },
                BlinkCmpKindValue                = { fg = colors.text, bg = blinkBg },
                BlinkCmpKindEnumMember           = { fg = colors.text, bg = blinkBg },
                BlinkCmpKindInterface            = { fg = colors.teal, bg = blinkBg },
                BlinkCmpKindColor                = { fg = colors.teal, bg = blinkBg },
                BlinkCmpKindTypeParameter        = { fg = colors.teal, bg = blinkBg },

                -------------------------------------------------------------------------------------------------------------
                -- MISC

                TSDefinitionUsage                = { bg = colors.surface0 },
                -- FloatBorder                      = { fg = colors.mantle, bg = colors.mantle },
                FloatBorder                      = { fg = colors.crust, bg = colors.crust },
                -- TSDefinition                     = { bg = colors.surface2 },
                Normal                           = { bg = colors.crust },
                NormalNC                         = { bg = colors.crust },
                NormalFloat                      = { fg = colors.text, bg = colors.mantle },
                LineNr                           = { fg = colors.surface0, bg = colors.crust },
                CursorLineNr                     = { fg = colors.text, bg = colors.crust },
                SagaFileName                     = { fg = colors.rosewater, bg = colors.mantle },
                NoiceCmdlineIcon                 = { fg = colors.rosewater },
                ActiveLineNumber                 = { fg = colors.subtext0 },
                Title                            = { fg = colors.subtext0 },
                MiniClueDescSingle               = { fg = colors.subtext0, bg = colors.crust },
                NoiceSplit                       = { fg = colors.subtext0, bg = colors.crust },
                VertSplit                        = { fg = colors.base, bg = colors.crust },
                WinBar                           = { fg = colors.subtext0, bg = colors.crust },
                WinBarNC                         = { fg = colors.subtext0, bg = colors.crust },
                LspInfoBorder                    = { fg = colors.subtext0, bg = colors.subtext0 },
                WinSeparator                     = { fg = colors.base, bg = colors.crust },
                SagaSep                          = { fg = colors.surface1, bg = colors.mantle },
                Visual                           = { fg = colors.red, bg = colors.mantle, bold = false },
                SignatureHelpBorder              = { fg = colors.mantle, bg = colors.mantle },
                HoverBorder                      = { fg = colors.mantle, bg = colors.mantle },
                RipSubBackdrop                   = { fg = colors.mantle, bg = colors.mantle },
                Folded                           = { fg = "NONE", bg = colors.mantle, bold = true },
                DiagnosticError                  = { bg = colors.crust },
                DiagnosticWarn                   = { bg = colors.crust },
                DiagnosticInfo                   = { bg = colors.crust },
                GitSignsAdd                      = { bg = colors.crust },
                GitSignsChange                   = { bg = colors.crust },
                GitSignsDelete                   = { bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- NEOTREE

                NeoTreeNormal                    = { fg = colors.text, bg = colors.crust },
                NeoTreeCursorLine                = { fg = "NONE", bg = colors.crust, bold = true },
                NeoTreeDirectoryIcon             = { fg = "#dce0e8" },
                NeoTreeFileName                  = { fg = colors.overlay2 },
                NeoTreeDirectoryName             = { fg = "#dce0e8" },
                NeoTreeExpander                  = { fg = colors.base },
                NeoTreeRootName                  = { fg = colors.flamingo },
                NeoTreeGitUntracked              = { fg = colors.lavender },
                NeoTreeGitModified               = { fg = colors.red },
                NeoTreeFloatTitle                = { fg = colors.crust, bg = colors.text },
                NeoTreeFloatBorder               = { fg = colors.text },
                NeoTreeFloatNormal               = { fg = colors.text },
                NeoTreeWinSeparator              = { fg = colors.base, bg = colors.crust },
                NeoTreeVertSplit                 = { fg = colors.surface0, bg = colors.crust },
                NeoTreeStatsHeader               = { fg = colors.base, bg = colors.base },
                NeoTreeModified                  = { fg = colors.text },
                NeoTreeNormalNC                  = { fg = colors.text, bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- TELESCOPE

                TelescopePromptCount             = { fg = colors.text, bg = colors.crust },
                TelescopePromptTitle             = { fg = colors.flamingo, bg = colors.crust },
                TelescopePromptPrefix            = { fg = colors.flamingo, bg = colors.crust },
                TelescopePromptNormal            = { fg = colors.text, bg = colors.crust },
                TelescopePromptBorder            = { fg = colors.crust, bg = colors.crust },
                TelescopeResultsTitle            = { fg = colors.flamingo, bg = colors.crust },
                TelescopeResultsNormal           = { fg = colors.overlay0, bg = colors.crust },
                TelescopeResultsBorder           = { fg = colors.crust, bg = colors.crust },
                TelescopePreviewTitle            = { fg = colors.text, bg = colors.crust },
                TelescopePreviewNormal           = { fg = colors.text, bg = colors.crust },
                TelescopePreviewBorder           = { fg = colors.mantle, bg = colors.crust },
                TelescopeSelection               = { fg = colors.red, bg = colors.crust },
                TelescopeSelectionCaret          = { fg = colors.red, bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- LUALINE
                lualine_a_insert                 = { fg = colors.crust, bg = colors.text },
                lualine_a_normal                 = { fg = colors.crust, bg = colors.text },
                lualine_a_visual                 = { fg = colors.crust, bg = colors.text },

                -------------------------------------------------------------------------------------------------------------
                -- OUTLINE
                OutlineCurrent                   = { fg = "NONE", bg = "NONE", bold = true },
                OutlineDetails                   = { fg = colors.surface1 },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR

                DropBarCurrentContext            = { fg = colors.overlay1 },
                DropBarFzfMatch                  = { fg = colors.red },
                DropBarHover                     = { fg = colors.overlay1 },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR ICON UI

                DropBarIconUiIndicator           = { fg = colors.surface1, bg = colors.mantle },
                DropBarIconUiPickpivot           = { fg = colors.red, bg = colors.crust },
                DropBarIconUiSeparator           = { fg = colors.surface1, bg = colors.crust },
                DropBarIconUiSeparatormenu       = { fg = colors.rosewater, bg = colors.mantle },
                -- DropBarFileName                  = { fg = "#dce0e8", italics = false },

                DropBarMenuCurrentContext        = { bg = colors.mantle, bold = true },
                DropBarMenuFloatBorder           = { fg = colors.rosewater, bg = colors.mantle },
                DropBarMenuHoverEntry            = { fg = colors.red, bg = colors.mantle },
                DropBarMenuHoverIcon             = { fg = colors.red, bg = colors.mantle, reverse = false },
                DropBarMenuHoverSymbol           = { fg = colors.rosewater, bg = colors.mantle, bold = true },
                DropBarMenuNormalFloat           = { fg = colors.rosewater, bg = colors.mantle },
                DropBarMenuSbar                  = { fg = colors.red, bg = colors.mantle },
                DropBarMenuThumb                 = { fg = colors.rosewater, bg = colors.mantle },
                DropBarPreview                   = { bg = colors.crust, bold = true },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR KIND

                DropBarKindDefault               = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindArray                 = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindBoolean               = { fg = colors.peach, bg = colors.crust },
                DropBarKindBreakstatement        = { fg = colors.lavender, bg = colors.crust },
                DropBarKindCall                  = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindCasestatement         = { fg = colors.lavender, bg = colors.crust },
                DropBarKindClass                 = { fg = "#dce0e8", bg = colors.crust },
                DropBarKindConstant              = { fg = colors.yellow, bg = colors.crust },
                DropBarKindConstructor           = { fg = colors.yellow, bg = colors.crust },
                DropBarKindContinuestatement     = { fg = colors.lavender, bg = colors.crust },
                DropBarKindDeclaration           = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindDelete                = { fg = colors.red, bg = colors.crust },
                DropBarKindDostatement           = { fg = colors.lavender, bg = colors.crust },
                DropBarKindElsestatement         = { fg = colors.lavender, bg = colors.crust },
                DropBarKindElement               = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindEnum                  = { fg = colors.lavender, bg = colors.crust },
                DropBarKindEnumMember            = { fg = colors.text, bg = colors.crust },
                DropBarKindEvent                 = { fg = colors.peach, bg = colors.crust },
                DropBarKindField                 = { fg = colors.lavender, bg = colors.crust },
                DropBarKindFile                  = { fg = colors.subtext0, bg = "NONE" },
                DropBarKindFolder                = { fg = "#dce0e8", bg = "NONE" },
                DropBarKindForStatement          = { fg = colors.lavender, bg = colors.crust },
                DropBarKindFunction              = { fg = "#dce0e8", bg = colors.crust },
                DropBarKindH1Marker              = { fg = colors.red, bg = colors.crust },
                DropBarKindH2Marker              = { fg = colors.peach, bg = colors.crust },
                DropBarKindH3Marker              = { fg = colors.yellow, bg = colors.crust },
                DropBarKindH4Marker              = { fg = colors.green, bg = colors.crust },
                DropBarKindH5Marker              = { fg = colors.sapphire, bg = colors.crust },
                DropBarKindH6Marker              = { fg = colors.lavender, bg = colors.crust },
                DropBarKindIdentifier            = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindIfStatement           = { fg = colors.lavender, bg = colors.crust },
                DropBarKindInterface             = { fg = colors.teal, bg = colors.crust },
                DropBarKindKeyword               = { fg = colors.lavender, bg = colors.crust },
                DropBarKindList                  = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindMacro                 = { fg = colors.mauve, bg = colors.crust },
                DropBarKindMarkdownH1            = { fg = colors.red, bg = colors.crust },
                DropBarKindMarkdownH2            = { fg = colors.peach, bg = colors.crust },
                DropBarKindMarkdownH3            = { fg = colors.yellow, bg = colors.crust },
                DropBarKindMarkdownH4            = { fg = colors.green, bg = colors.crust },
                DropBarKindMarkdownH5            = { fg = colors.sapphire, bg = colors.crust },
                DropBarKindMarkdownH6            = { fg = colors.lavender, bg = colors.crust },
                DropBarKindMethod                = { fg = colors.text, bg = colors.crust },
                DropBarKindModule                = { fg = "#dce0e8", bg = colors.crust },
                DropBarKindNamespace             = { fg = colors.mauve, bg = colors.crust },
                DropBarKindNull                  = { fg = colors.peach, bg = colors.crust },
                DropBarKindNumber                = { fg = colors.maroon, bg = colors.crust },
                DropBarKindObject                = { fg = colors.lavender, bg = colors.crust },
                DropBarKindOperator              = { fg = "#dce0e8", bg = colors.crust },
                DropBarKindPackage               = { fg = colors.sapphire, bg = colors.crust },
                DropBarKindPair                  = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindProperty              = { fg = colors.lavender, bg = colors.crust },
                DropBarKindReference             = { fg = colors.yellow, bg = colors.crust },
                DropBarKindRepeat                = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindRuleset               = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindScope                 = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindSpecifier             = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindStatement             = { fg = colors.lavender, bg = colors.crust },
                DropBarKindString                = { fg = colors.green, bg = colors.crust },
                DropBarKindStruct                = { fg = "#dce0e8", bg = colors.crust },
                DropBarKindSwitchstatement       = { fg = colors.lavender, bg = colors.crust },
                DropBarKindTerminal              = { fg = colors.rosewater, bg = colors.crust },
                DropBarKindType                  = { fg = colors.teal, bg = colors.crust },
                DropBarKindTypeParameter         = { fg = colors.teal, bg = colors.crust },
                DropBarKindUnit                  = { fg = colors.yellow, bg = colors.crust },
                DropBarKindValue                 = { fg = colors.text, bg = colors.crust },
                DropBarKindVariable              = { fg = colors.red, bg = colors.crust },
                DropBarKindWhileStatement        = { fg = colors.lavender, bg = colors.crust },

                -------------------------------------------------------------------------------------------------------------
                -- DROPBAR ICON KIND

                DropBarIconKindFile              = { fg = colors.subtext0, bg = colors.crust },
                DropBarIconKindModule            = { fg = "#dce0e8", bg = colors.crust },
                DropBarIconKindNamespace         = { fg = colors.mauve, bg = colors.crust },
                DropBarIconKindPackage           = { fg = colors.sapphire, bg = colors.crust },
                DropBarIconKindClass             = { fg = "#dce0e8", bg = colors.crust },
                DropBarIconKindMethod            = { fg = colors.text, bg = colors.crust },
                DropBarIconKindProperty          = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindField             = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindConstructor       = { fg = colors.yellow, bg = colors.crust },
                DropBarIconKindEnum              = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindInterface         = { fg = colors.teal, bg = colors.crust },
                DropBarIconKindFunction          = { fg = "#dce0e8", bg = colors.crust },
                DropBarIconKindVariable          = { fg = colors.red, bg = colors.crust },
                DropBarIconKindConstant          = { fg = colors.yellow, bg = colors.crust },
                DropBarIconKindString            = { fg = colors.green, bg = colors.crust },
                DropBarIconKindNumber            = { fg = colors.maroon, bg = colors.crust },
                DropBarIconKindBoolean           = { fg = colors.peach, bg = colors.crust },
                DropBarIconKindArray             = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindObject            = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindKeyword           = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindNull              = { fg = colors.peach, bg = colors.crust },
                DropBarIconKindEnumMember        = { fg = colors.text, bg = colors.crust },
                DropBarIconKindStruct            = { fg = "#dce0e8", bg = colors.crust },
                DropBarIconKindEvent             = { fg = colors.peach, bg = colors.crust },
                DropBarIconKindOperator          = { fg = "#dce0e8", bg = colors.crust },
                DropBarIconKindTypeParameter     = { fg = colors.teal, bg = colors.crust },
                DropBarIconKindDefault           = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindBreakStatement    = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindCall              = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindCaseStatement     = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindContinueStatement = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindDeclaration       = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindDelete            = { fg = colors.red, bg = colors.crust },
                DropBarIconKindDoStatement       = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindElseStatement     = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindElement           = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindFolder            = { fg = "#dce0e8", bg = "NONE" },
                DropBarIconKindForStatement      = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindH1Marker          = { fg = colors.red, bg = colors.crust },
                DropBarIconKindH2Marker          = { fg = colors.peach, bg = colors.crust },
                DropBarIconKindH3Marker          = { fg = colors.yellow, bg = colors.crust },
                DropBarIconKindH4Marker          = { fg = colors.green, bg = colors.crust },
                DropBarIconKindH5Marker          = { fg = colors.sapphire, bg = colors.crust },
                DropBarIconKindH6Marker          = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindIdentifier        = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindIfstatement       = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindList              = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindMacro             = { fg = colors.mauve, bg = colors.crust },
                DropBarIconKindMarkdownH1        = { fg = colors.red, bg = colors.crust },
                DropBarIconKindMarkdownH2        = { fg = colors.peach, bg = colors.crust },
                DropBarIconKindMarkdownH3        = { fg = colors.yellow, bg = colors.crust },
                DropBarIconKindMarkdownH4        = { fg = colors.green, bg = colors.crust },
                DropBarIconKindMarkdownH5        = { fg = colors.sapphire, bg = colors.crust },
                DropBarIconKindMarkdownH6        = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindPair              = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindReference         = { fg = colors.yellow, bg = colors.crust },
                DropBarIconKindRepeat            = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindRuleset           = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindScope             = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindSpecifier         = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindStatement         = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindSwitchStatement   = { fg = colors.lavender, bg = colors.crust },
                DropBarIconKindTerminal          = { fg = colors.rosewater, bg = colors.crust },
                DropBarIconKindType              = { fg = colors.teal, bg = colors.crust },
                DropBarIconKindUnit              = { fg = colors.yellow, bg = colors.crust },
                DropBarIconKindValue             = { fg = colors.text, bg = colors.crust },
                DropBarIconKindWhileStatement    = { fg = colors.lavender, bg = colors.crust },
        }
end

return {
        "catppuccin/nvim",
        lazy     = false,
        name     = "catppuccin",
        priority = 1000,
        config   = function()
                require("catppuccin").setup({
                        compile_path           = vim.fn.stdpath "cache" .. "/catppuccin",
                        flavour                = "mocha",
                        transparent_background = false,
                        show_end_of_buffer     = true,
                        term_colors            = true,
                        background             = { light = "latte", dark = "mocha" },
                        dim_inactive           = { enabled = false, shade = "dark", percentage = 0.15 },
                        no_italic              = true,
                        no_bold                = false,
                        no_underline           = false,

                        color_overrides        = {
                                mocha = {
                                        -- crust  = "#000000",
                                        -- mantle = "#000000",
                                }
                        },
                        custom_highlights      = customCol,

                        default_integrations   = true,
                        integrations           = {
                                blink_cmp        = true,
                                cmp              = true,
                                dap              = true,
                                dap_ui           = true,
                                lsp_saga         = true,
                                dashboard        = true,
                                dropbar          = {
                                        enabled    = true,
                                        color_mode = true
                                },
                                gitsigns         = true,
                                indent_blankline = {
                                        enabled     = true,
                                        scope_color = "text",
                                },
                                mason            = true,
                                markdown         = true,
                                render_markdown  = true,
                                mini             = true,
                                native_lsp       = {
                                        enabled    = true,
                                        underlines = {
                                                -- errors      = { "undercurl" },
                                                -- hints       = { "undercurl" },
                                                -- warnings    = { "undercurl" },
                                                -- information = { "undercurl" },
                                        },
                                },
                                telescope        = true,
                                notify           = true,
                                navic            = { enabled = true, custom_bg = "lualine" },
                                neotest          = true,
                                neotree          = true,
                                noice            = true,
                                semantic_tokens  = true,
                                treesitter       = true,
                                ufo              = true,
                                which_key        = true,
                        },
                })

                vim.cmd("colorscheme catppuccin")
        end,
}
