local devicons = {
        Array             = "󰅪 ",
        Boolean           = " ",
        BreakStatement    = "󰙧 ",
        Call              = "󰃷 ",
        CaseStatement     = "󱃙 ",
        Class             = " ",
        Color             = " ",
        Constant          = " ",
        Constructor       = " ",
        ContinueStatement = "→ ",
        Copilot           = " ",
        Declaration       = "󰙠 ",
        Delete            = "󰢤 ",
        DoStatement       = "󰑖 ",
        Enum              = " ",
        EnumMember        = " ",
        Event             = " ",
        Field             = " ",
        File              = " ",
        Folder            = " ",
        ForStatement      = "󰑖 ",
        Function          = " ",
        H1Marker          = "󰉫 ",
        H2Marker          = "󰉬 ",
        H3Marker          = "󰉭 ",
        H4Marker          = "󰉮 ",
        H5Marker          = "󰉯 ",
        H6Marker          = "󰉰 ",
        Identifier        = " ",
        IfStatement       = " ",
        Interface         = " ",
        Keyword           = " ",
        List              = "󰅪 ",
        Log               = " ",
        Lsp               = " ",
        Macro             = " ",
        MarkdownH1        = "󰉫 ",
        MarkdownH2        = "󰉬 ",
        MarkdownH3        = "󰉭 ",
        MarkdownH4        = "󰉮 ",
        MarkdownH5        = "󰉯 ",
        MarkdownH6        = "󰉰 ",
        Method            = " ",
        Module            = " ",
        Namespace         = " ",
        Null              = "󰢤 ",
        Number            = "󰎠 ",
        Object            = " ",
        Operator          = "󰆕 ",
        Package           = " ",
        Pair              = "󰅪 ",
        Property          = " ",
        Reference         = "󰈇 ",
        Regex             = " ",
        Repeat            = "󰑖 ",
        Scope             = " ",
        Snippet           = " ",
        Specifier         = "󰦪 ",
        Statement         = " ",
        String            = "󰉾 ",
        Struct            = " ",
        SwitchStatement   = "󰺟 ",
        Terminal          = " ",
        Text              = " ",
        Type              = " ",
        TypeParameter     = " ",
        Unit              = " ",
        Value             = "󰎠 ",
        Variable          = " ",
        WhileStatement    = "󰑖 ",
}

return {
        "Bekaboo/dropbar.nvim",
        event        = "VeryLazy",
        dependencies = { "nvim-telescope/telescope-fzf-native.nvim" },
        keys         = {
                { "<A-q>", function() require("dropbar.api").pick() end, desc = "Toggle dropbar", mode = { "n" } },
        },

        opts         = {
                bar   = { truncate = true, pick = { pivots = "hjklHJKL" } },
                icons = {
                        enable = true,
                        kinds  = {
                                ui      = { bar = { separator = " > ", extends = "…" }, menu = { separator = "", indicator = " 󰨓  " } },
                                symbols = devicons,
                        },
                },
        },
}
